export const GET_ALL_WAREHOUSE = "GET_ALL_WAREHOUSE";
export const GET_ALL_WAREHOUSE_SUCCESS = "GET_ALL_WAREHOUSE_SUCCESS";
export const GET_ALL_WAREHOUSE_FAILURE = "GET_ALL_WAREHOUSE_FAILURE";

export const NEW_WAREHOUSE = "NEW_WAREHOUSE";
export const NEW_WAREHOUSE_SUCCESS = "NEW_WAREHOUSE_SUCCESS";
export const NEW_WAREHOUSE_FAILURE = "NEW_WAREHOUSE_FAILURE";

export const EDIT_WAREHOUSE = "EDIT_WAREHOUSE";
export const EDIT_WAREHOUSE_SUCCESS = "EDIT_WAREHOUSE_SUCCESS";
export const EDIT_WAREHOUSE_FAILURE = "EDIT_WAREHOUSE_FAILURE";

export const DELETE_WAREHOUSE = "DELETE_WAREHOUSE";
export const DELETE_WAREHOUSE_SUCCESS = "DELETE_WAREHOUSE_SUCCESS";
export const DELETE_WAREHOUSE_FAILURE = "DELETE_WAREHOUSE_FAILURE";
