export const GET_WAREHOUSE_HEALTH = "GET_WAREHOUSE_HEALTH";
export const GET_WAREHOUSE_HEALTH_SUCCESS = "GET_WAREHOUSE_HEALTH_SUCCESS";
export const GET_WAREHOUSE_HEALTH_FAILURE = "GET_WAREHOUSE_HEALTH_FAILURE";
