"""empty message

Revision ID: 50f32f00ecdd
Revises: 
Create Date: 2019-10-04 09:55:59.260276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50f32f00ecdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    op.alter_column(u'employees', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column(u'inventory', 'name',
               existing_type=mysql.TEXT(collation=u'utf8_bin'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column(u'loctite', 'description',
               existing_type=mysql.TEXT(collation=u'utf8_bin'),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'loctite', 'description',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(collation=u'utf8_bin'),
               existing_nullable=True)
    op.alter_column(u'inventory', 'name',
               existing_type=sa.String(length=50),
               type_=mysql.TEXT(collation=u'utf8_bin'),
               existing_nullable=True)
    op.alter_column(u'employees', 'is_admin',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_table('auditlog')
    # ### end Alembic commands ###
