"""empty message

Revision ID: dfbe251b8beb
Revises: 
Create Date: 2020-05-14 20:04:01.225904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfbe251b8beb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventoryorders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('current', sa.Integer(), nullable=True),
    sa.Column('adjustment_type', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loctiteorders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('current', sa.Integer(), nullable=True),
    sa.Column('adjustment_type', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'auditlog', sa.Column('product', sa.String(length=255), nullable=True))
    op.alter_column(u'employees', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_constraint(u'inventory_ibfk_2', 'inventory', type_='foreignkey')
    op.drop_constraint(u'inventory_ibfk_1', 'inventory', type_='foreignkey')
    op.create_foreign_key(None, 'inventory', 'warehouse', ['wid'], ['wid'])
    op.create_foreign_key(None, 'inventory', 'category', ['cid'], ['cid'])
    op.alter_column(u'todolist', 'done',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'todolist', 'done',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.create_foreign_key(u'inventory_ibfk_1', 'inventory', 'warehouse', ['wid'], ['wid'], onupdate=u'CASCADE', ondelete=u'SET NULL')
    op.create_foreign_key(u'inventory_ibfk_2', 'inventory', 'category', ['cid'], ['cid'], onupdate=u'CASCADE', ondelete=u'SET NULL')
    op.alter_column(u'employees', 'is_admin',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column(u'auditlog', 'product')
    op.drop_table('loctiteorders')
    op.drop_table('inventoryorders')
    # ### end Alembic commands ###
