/**
 * Report Actions
 */
// Edit History Report
export const GET_EDIT_HISTORY_INV = "GET_EDIT_HISTORY_INV";
export const GET_EDIT_HISTORY_INV_SUCCESS = "GET_EDIT_HISTORY_INV_SUCCESS";

export const GET_EDIT_HISTORY_LOC = "GET_EDIT_HISTORY_LOC";
export const GET_EDIT_HISTORY_LOC_SUCCESS = "GET_EDIT_HISTORY_LOC_SUCCESS";

export const GET_REPORT_FAILURE = "GET_REPORT_FAILURE";
