export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";
export const GET_ALL_CATEGORIES_FAILURE = "GET_ALL_CATEGORIES_FAILURE";

export const NEW_CATEGORIES = "NEW_CATEGORIES";
export const NEW_CATEGORIES_SUCCESS = "NEW_CATEGORIES_SUCCESS";
export const NEW_CATEGORIES_FAILURE = "NEW_CATEGORIES_FAILURE";

export const EDIT_CATEGORIES = "EDIT_CATEGORIES";
export const EDIT_CATEGORIES_SUCCESS = "EDIT_CATEGORIES_SUCCESS";
export const EDIT_CATEGORIES_FAILURE = "EDIT_CATEGORIES_FAILURE";

export const DELETE_CATEGORIES = "DELETE_CATEGORIES";
export const DELETE_CATEGORIES_SUCCESS = "DELETE_CATEGORIES_SUCCESS";
export const DELETE_CATEGORIES_FAILURE = "DELETE_CATEGORIES_FAILURE";
