// Loctite Actions

// get
export const LOCTITE_API_FAILURE = "LOCTITE_API_FAILURE";
export const GET_ALL_LOCTITE = "GET_ALL_LOCTITE";
export const GET_ALL_LOCTITE_SUCCESS = "GET_ALL_LOCTITE_SUCCESS";
// view loctite
export const VIEW_LOCTITE = "VIEW_LOCTITE";
export const VIEW_LOCTITE_SUCCESS = "VIEW_LOCTITE_SUCCESS";
export const ON_CHANGE_LOCTITE_LIST = "ON_CHANGE_LOCTITE_LIST";
// new loctite
export const SUBMIT_LOCTITE_FORM = "SUBMIT_LOCTITE_FORM";
export const SUBMIT_LOCTITE_SUCCESS = "SUBMIT_LOCTITE_SUCCESS";
export const SUBMIT_LOCTITE_FAILURE = "SUBMIT_LOCTITE_FAILURE";
export const HANDLE_LOCTITE_FORM = "HANDLE_LOCTITE_FORM";
export const CLEAR_LOCTITE_FORM = "CLEAR_LOCTITE_FORM";
// edit
export const START_EDIT_LOCTITE = "START_EDIT_LOCTITE";
export const START_EDIT_LOCTITE_SUCCESS = "START_EDIT_LOCTITE_SUCCESS";
export const START_EDIT_LOCTITE_FAILURE = "START_EDIT_LOCTITE_FAILURE";

export const EDIT_LOCTITE = "EDIT_LOCTITE";
export const EDIT_LOCTITE_SUCCESS = "EDIT_LOCTITE_SUCCESS";
export const EDIT_LOCTITE_FAILURE = "EDIT_LOCTITE_FAILURE";

// Delete
export const DELETE_LOCTITE = "DELETE_LOCTITE";
export const DELETE_LOCTITE_SUCCESS = "DELETE_LOCTITE_SUCCESS";
export const DELETE_LOCTITE_FAILURE = "DELETE_LOCTITE_FAILURE";

// Mass update
export const MASS_UPDATE_LOCTITE = "MASS_UPDATE_LOCTITE";
export const MASS_UPDATE_LOCTITE_SUCCESS = "MASS_UPDATE_LOCTITE_SUCCESS";
export const MASS_UPDATE_LOCTITE_FAILURE = "MASS_UPDATE_LOCTITE_FAILURE";

export const MASS_UPDATE_FILTER_LOCTITE = "MASS_UPDATE_FILTER_LOCTITE";
export const MASS_UPDATE_FILTER_LOCTITE_SUCCESS =
  "MASS_UPDATE_FILTER_LOCTITE_SUCCESS";
export const MASS_UPDATE_FILTER_LOCTITE_FAILURE =
  "MASS_UPDATE_FILTER_LOCTITE_FAILURE";
export const CLEAR_UPDATE_FILTER_LOCTITE = "CLEAR_UPDATE_FILTER_LOCTITE";

export const REMOVE_FROM_LOC_LIST = "REMOVE_FROM_LOC_LIST";
export const ADD_TO_LOC_LIST = "ADD_TO_LOC_LIST";

// Stock update
export const LOC_STOCK_UPDATE = "LOC_STOCK_UPDATE";
export const LOC_STOCK_UPDATE_SUCCESS = "LOC_STOCK_UPDATE_SUCCESS";
export const LOC_STOCK_UPDATE_FAILURE = "LOC_STOCK_UPDATE_FAILURE";
