// Warehouse Actions
export const GET_WAREHOUSE_FIELD = "GET_WAREHOUSE_FIELD";
export const GET_WAREHOUSE_FIELD_SUCCESS = "GET_WAREHOUSE_FIELD_SUCCESS";
export const GET_WAREHOUSE_FIELD_FAILURE = "GET_WAREHOUSE_FIELD_FAILURE";

// Categories Actions
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";
