// Inventory Actions

// Get
export const INVENTORY_API_FAILURE = "INVENTORY_API_FAILURE";
export const GET_ALL_INVENTORY = "GET_ALL_INVENTORY";
export const GET_ALL_INVENTORY_SUCCESS = "GET_ALL_INVENTORY_SUCCESS";

// view inventory
export const GET_INVENTORY = "GET_INVENTORY";
export const GET_INVENTORY_SUCCESS = "GET_INVENTORY_SUCCESS";
// new inventory
export const SUBMIT_INVENTORY_FORM = "SUBMIT_INVENTORY_FORM";
export const SUBMIT_INVENTORY_SUCCESS = "SUBMIT_INVENTORY_SUCCESS";
export const SUBMIT_INVENTORY_FAILURE = "SUBMIT_INVENTORY_FAILURE";
export const CLEAR_INVENTORY_FORM = "CLEAR_INVENTORY_FORM";
export const HANDLE_INV_FORM_CHANGE = "HANDLE_INV_FORM_CHANGE";
// edit
export const START_EDIT_INVENTORY = "START_EDIT_INVENTORY";
export const START_EDIT_INVENTORY_SUCCESS = "START_EDIT_INVENTORY_SUCCESS";
export const START_EDIT_INVENTORY_FAILURE = "START_EDIT_INVENTORY_FAILURE";

export const EDIT_INVENTORY = "EDIT_INVENTORY";
export const EDIT_INVENTORY_SUCCESS = "EDIT_INVENTORY_SUCCESS";
export const EDIT_INVENTORY_FAILURE = "EDIT_INVENTORY_FAILURE";

// Delete
export const DELETE_INVENTORY = "DELETE_INVENTORY";
export const DELETE_INVENTORY_SUCCESS = "DELETE_INVENTORY_SUCCESS";
export const DELETE_INVENTORY_FAILURE = "DELETE_INVENTORY_FAILURE";

// Mass update
export const MASS_UPDATE_INVENTORY = "MASS_UPDATE_INVENTORY";
export const MASS_UPDATE_INVENTORY_SUCCESS = "MASS_UPDATE_INVENTORY_SUCCESS";
export const MASS_UPDATE_INVENTORY_FAILURE = "MASS_UPDATE_INVENTORY_FAILURE";

export const MASS_UPDATE_FILTER_INVENTORY = "MASS_UPDATE_FILTER_INVENTORY";
export const MASS_UPDATE_FILTER_INVENTORY_SUCCESS =
  "MASS_UPDATE_FILTER_INVENTORY_SUCCESS";
export const MASS_UPDATE_FILTER_INVENTORY_FAILURE =
  "MASS_UPDATE_FILTER_INVENTORY_FAILURE";
export const CLEAR_UPDATE_FILTER_INVENTORY = "CLEAR_UPDATE_FILTER_INVENTORY";

export const REMOVE_FROM_INV_LIST = "REMOVE_FROM_INV_LIST";
export const ADD_TO_INV_LIST = "ADD_TO_INV_LIST";

// Stock update
export const INV_STOCK_UPDATE = "INV_STOCK_UPDATE";
export const INV_STOCK_UPDATE_SUCCESS = "INV_STOCK_UPDATE_SUCCESS";
export const INV_STOCK_UPDATE_FAILURE = "INV_STOCK_UPDATE_FAILURE";

// Show Inventory without filter
export const SHOW_ALL_INVENTORY = "SHOW_ALL_INVENTORY";
export const SHOW_ALL_INVENTORY_SUCCESS = "SHOW_ALL_INVENTORY_SUCCESS";
export const SHOW_ALL_INVENTORY_FAILURE = "SHOW_ALL_INVENTORY_FAILURE";
